name: Doc Generation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  docgen:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:			
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull --no-ff --allow-unrelated-histories origin ${{ github.event.pull_request.head.ref }}

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "🤖 Running documentation generation script..."

      - name: Run docgen script
        run: |
          ~/.bun/bin/bun run docgen.ts

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: docgen
          path: .
          compression-level: 1
          if-no-files-found: error
          retention-days: 1

  commit:
    needs: [docgen]
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref}}
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN}}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: docgen

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -a -m "Update README.md with latest documentation [skip actions]" || exit 0

      - name: Pull latest changes
        run: |
          git config pull.rebase false
          git pull --no-ff --allow-unrelated-histories origin ${{ github.event.pull_request.head.ref }} || true
          git merge --strategy-option theirs || true

      - name: Push version changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: master
          force_with_lease: true

  success:
    needs: [commit]
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "🤖 Documentation generation complete. README.md updated.\nHave a nice day!"

  error:
    needs: [docgen, commit]
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "🤖 Documentation generation failed. Please check the logs for more information."