name: Zig Utils

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create a temporary folder
        run: |
          if ! mkdir -p tmp; then
            echo "Failed to create the folder"
            exit 1
          fi

      - name: Download raw file
        run: |
          if ! curl https://raw.githubusercontent.com/gaskam-com/zig-utils/refs/heads/main/LineReader.zig -o "tmp/LineReader.txt"; then
            echo "Failed to download the file"
            exit 1
          fi

      - name: Get the actual template
        run: |
          sed -n '/"zig utils": {/,/}/p' "snippets/snippets.code-snippets" \
          | grep '"body":' \
          | sed -E 's/.*"body": *\[//; s/\].*//g' > tmp/snippets_body.txt

      - name: Upload tmp directory
        uses: actions/upload-artifact@v4.4.3
        with:
          name: tmp
          path: tmp/

  format:
    runs-on: ubuntu-latest
    needs: initialize 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tmp directory
        uses: actions/download-artifact@v4.1.8
        with:
          name: tmp
          path: tmp/

      - name: Check if the file exists
        run: |
          if [ -f "tmp/LineReader.txt" ]; then
            echo "File exists"
          else
            echo "File does not exist: tmp/LineReader.txt"
            exit 1
          fi
          if [ -f "tmp/snippets_body.txt" ]; then
            echo "File exists"
          else
            echo "File does not exist: tmp/snippets_body.txt"
            exit 1
          fi

      - name: Format the file
        run: |
          sed -e 's/\\t/\\\\t/g' -e 's/\\n/\\\\n/g' -e 's/"/\\"/g' tmp/LineReader.txt \
          sed 's/    /\t/g' \
          awk '{ print "\"" $0 "\"," }' \
          sed '$ s/,$//' > tmp/LineReader.txt

      - name: Upload formatted tmp directory
        uses: actions/upload-artifact@v4.4.3
        with:
          name: tmp
          path: tmp/

  compare:
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tmp directory
        uses: actions/download-artifact@v4.1.8
        with:
          name: tmp
          path: tmp/

      - name: Compare the files
        run: |
          if ! diff -q tmp/LineReader.txt tmp/snippets_body.txt; then
            echo "Files are different"
            content=$(cat tmp/LineReader.txt)
            jq --arg content "$content" '."zig utils".body = [$content]' snippets/snippets.code-snippets > temp.json && mv temp.json snippets/snippets.code-snippets
            
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add snippets/snippets.code-snippets
            git commit -m "Update zig utils snippet"
            git push origin HEAD:update-zig-utils
          else
            echo "Files are the same"
            exit 0
          fi
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit-message: Update zig utils snippet
          title: 'Update zig utils snippet'
          body: 'Automated PR to update zig utils snippet'
          branch: update-zig-utils
          delete-branch: true